#!/bin/bash
GROUP=clusterography
export PATH=/home/gustas/software/CASM_coupled:$PATH
cd /home/gustas/software/CASM_coupled
mkdir -p /home/gustas/software/CASM_coupled/tests/unit/test_projects
: ${TEST_FLAGS:="--log_level=test_suite --catch_system_errors=no"}
/home/gustas/software/CASM_coupled/casm_unit_$GROUP ${TEST_FLAGS}
