#!/bin/bash
GROUP=system
export PATH=/home/gustas/software/CASM_cpld_og_dev:$PATH
cd /home/gustas/software/CASM_cpld_og_dev
mkdir -p /home/gustas/software/CASM_cpld_og_dev/tests/unit/test_projects
: ${TEST_FLAGS:="--log_level=test_suite --catch_system_errors=no"}
/home/gustas/software/CASM_cpld_og_dev/casm_unit_$GROUP ${TEST_FLAGS}
