#!/bin/bash
GROUP=system
export PATH=/home/gustas/software/CASM_cpld_dev_3:$PATH
cd /home/gustas/software/CASM_cpld_dev_3
mkdir -p /home/gustas/software/CASM_cpld_dev_3/tests/unit/test_projects
: ${TEST_FLAGS:="--log_level=test_suite --catch_system_errors=no"}
/home/gustas/software/CASM_cpld_dev_3/casm_unit_$GROUP ${TEST_FLAGS}
